<?php

namespace App\Tasks\Kong\Services;

use App\Common\Clients\KongClient;
use App\Common\Enums\ErrorCode;
use App\Common\Exceptions\BizException;
use App\Tasks\Kong\KongTask;
use App\Tasks\Task;

class UpdateTask extends KongTask
{
    public function onConstruct()
    {
        $config = di('configCenter')->get('kong')->service;
        $this->params = $config->params->toArray();
        parent::onConstruct(); // TODO: Change the autogenerated stub
    }

    public function handle($params = [])
    {
        $id = $this->getIdOrName();
        $client = KongClient::getInstance();
        $res = $client->updateService($id, $params);
        $this->dump($res);
    }
}
